# database configs
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mv_sistemas?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    dialect: org.hibernate.dialect.MySQL5Dialect